{% set name = "pytest-datadir" %}
{% set version = "1.6.1" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4d204cf93cfe62ddc37b19922df6c8c0f133c2899c224bd339b24920e84e7fd3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pytest >=7.0

test:
  requires:
    - pytest
    - python {{ python_min }}
  imports:
    - pytest_datadir
  commands:
    - pytest --help

about:
  home: https://github.com/gabrielcnr/pytest-datadir
  license: MIT
  license_file: LICENSE
  summary: pytest plugin for manipulating test data directories and files.

extra:
  recipe-maintainers:
    - nicoddemus
    - gabrielcnr
    - edisongustavo
    - gqmelo
    - IgorTG
